// Copyright 2024 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file alphagenome/protos/dna_model_service.proto (package google.gdm.gdmscience.alphagenome.v1main, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MetadataRequest, MetadataResponse, PredictIntervalRequest, PredictIntervalResponse, PredictSequenceRequest, PredictSequenceResponse, PredictVariantRequest, PredictVariantResponse, ScoreIntervalRequest, ScoreIntervalResponse, ScoreIsmVariantRequest, ScoreIsmVariantResponse, ScoreVariantRequest, ScoreVariantResponse } from "./dna_model_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service for making predictions with DNA models.
 *
 * @generated from service google.gdm.gdmscience.alphagenome.v1main.DnaModelService
 */
export const DnaModelService = {
  typeName: "google.gdm.gdmscience.alphagenome.v1main.DnaModelService",
  methods: {
    /**
     * Makes a prediction for DNA sequence.
     *
     * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.PredictSequence
     */
    predictSequence: {
      name: "PredictSequence",
      I: PredictSequenceRequest,
      O: PredictSequenceResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Make prediction for a single genomic interval.
     *
     * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.PredictInterval
     */
    predictInterval: {
      name: "PredictInterval",
      I: PredictIntervalRequest,
      O: PredictIntervalResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Make variant effect predictions for a genomic interval.
     *
     * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.PredictVariant
     */
    predictVariant: {
      name: "PredictVariant",
      I: PredictVariantRequest,
      O: PredictVariantResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Score a genomic interval.
     *
     * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.ScoreInterval
     */
    scoreInterval: {
      name: "ScoreInterval",
      I: ScoreIntervalRequest,
      O: ScoreIntervalResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Score a variant for a genomic interval.
     *
     * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.ScoreVariant
     */
    scoreVariant: {
      name: "ScoreVariant",
      I: ScoreVariantRequest,
      O: ScoreVariantResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Score ISM variant effect predictions for a genomic interval.
     *
     * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.ScoreIsmVariant
     */
    scoreIsmVariant: {
      name: "ScoreIsmVariant",
      I: ScoreIsmVariantRequest,
      O: ScoreIsmVariantResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Get metadata for the model.
     *
     * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.GetMetadata
     */
    getMetadata: {
      name: "GetMetadata",
      I: MetadataRequest,
      O: MetadataResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

