// Copyright 2024 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file alphagenome/protos/dna_model_service.proto (package google.gdm.gdmscience.alphagenome.v1main, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { MetadataRequestSchema, MetadataResponseSchema, PredictIntervalRequestSchema, PredictIntervalResponseSchema, PredictSequenceRequestSchema, PredictSequenceResponseSchema, PredictVariantRequestSchema, PredictVariantResponseSchema, ScoreIntervalRequestSchema, ScoreIntervalResponseSchema, ScoreIsmVariantRequestSchema, ScoreIsmVariantResponseSchema, ScoreVariantRequestSchema, ScoreVariantResponseSchema } from "./dna_model_pb";
import { file_alphagenome_protos_dna_model } from "./dna_model_pb";

/**
 * Describes the file alphagenome/protos/dna_model_service.proto.
 */
export const file_alphagenome_protos_dna_model_service: GenFile = /*@__PURE__*/
  fileDesc("CiphbHBoYWdlbm9tZS9wcm90b3MvZG5hX21vZGVsX3NlcnZpY2UucHJvdG8SKGdvb2dsZS5nZG0uZ2Rtc2NpZW5jZS5hbHBoYWdlbm9tZS52MW1haW4yxAgKD0RuYU1vZGVsU2VydmljZRKcAQoPUHJlZGljdFNlcXVlbmNlEkAuZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5QcmVkaWN0U2VxdWVuY2VSZXF1ZXN0GkEuZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5QcmVkaWN0U2VxdWVuY2VSZXNwb25zZSIAKAEwARKcAQoPUHJlZGljdEludGVydmFsEkAuZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5QcmVkaWN0SW50ZXJ2YWxSZXF1ZXN0GkEuZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5QcmVkaWN0SW50ZXJ2YWxSZXNwb25zZSIAKAEwARKZAQoOUHJlZGljdFZhcmlhbnQSPy5nb29nbGUuZ2RtLmdkbXNjaWVuY2UuYWxwaGFnZW5vbWUudjFtYWluLlByZWRpY3RWYXJpYW50UmVxdWVzdBpALmdvb2dsZS5nZG0uZ2Rtc2NpZW5jZS5hbHBoYWdlbm9tZS52MW1haW4uUHJlZGljdFZhcmlhbnRSZXNwb25zZSIAKAEwARKWAQoNU2NvcmVJbnRlcnZhbBI+Lmdvb2dsZS5nZG0uZ2Rtc2NpZW5jZS5hbHBoYWdlbm9tZS52MW1haW4uU2NvcmVJbnRlcnZhbFJlcXVlc3QaPy5nb29nbGUuZ2RtLmdkbXNjaWVuY2UuYWxwaGFnZW5vbWUudjFtYWluLlNjb3JlSW50ZXJ2YWxSZXNwb25zZSIAKAEwARKTAQoMU2NvcmVWYXJpYW50Ej0uZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5TY29yZVZhcmlhbnRSZXF1ZXN0Gj4uZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5TY29yZVZhcmlhbnRSZXNwb25zZSIAKAEwARKcAQoPU2NvcmVJc21WYXJpYW50EkAuZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5TY29yZUlzbVZhcmlhbnRSZXF1ZXN0GkEuZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5TY29yZUlzbVZhcmlhbnRSZXNwb25zZSIAKAEwARKIAQoLR2V0TWV0YWRhdGESOS5nb29nbGUuZ2RtLmdkbXNjaWVuY2UuYWxwaGFnZW5vbWUudjFtYWluLk1ldGFkYXRhUmVxdWVzdBo6Lmdvb2dsZS5nZG0uZ2Rtc2NpZW5jZS5hbHBoYWdlbm9tZS52MW1haW4uTWV0YWRhdGFSZXNwb25zZSIAMAFCmwEKLGNvbS5nb29nbGUuZ2RtLmdkbXNjaWVuY2UuYWxwaGFnZW5vbWUudjFtYWluQhREbmFNb2RlbFNlcnZpY2VQcm90b1ABWlNnb29nbGUuZ29sYW5nLm9yZy9nZW5wcm90by9nb29nbGVhcGlzL2dkbS9nZG1zY2llbmNlL2FscGhhZ2Vub21lL3YxbWFpbjthbHBoYWdlbm9tZWIGcHJvdG8z", [file_alphagenome_protos_dna_model]);

/**
 * Service for making predictions with DNA models.
 *
 * @generated from service google.gdm.gdmscience.alphagenome.v1main.DnaModelService
 */
export const DnaModelService: GenService<{
  /**
   * Makes a prediction for DNA sequence.
   *
   * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.PredictSequence
   */
  predictSequence: {
    methodKind: "bidi_streaming";
    input: typeof PredictSequenceRequestSchema;
    output: typeof PredictSequenceResponseSchema;
  },
  /**
   * Make prediction for a single genomic interval.
   *
   * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.PredictInterval
   */
  predictInterval: {
    methodKind: "bidi_streaming";
    input: typeof PredictIntervalRequestSchema;
    output: typeof PredictIntervalResponseSchema;
  },
  /**
   * Make variant effect predictions for a genomic interval.
   *
   * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.PredictVariant
   */
  predictVariant: {
    methodKind: "bidi_streaming";
    input: typeof PredictVariantRequestSchema;
    output: typeof PredictVariantResponseSchema;
  },
  /**
   * Score a genomic interval.
   *
   * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.ScoreInterval
   */
  scoreInterval: {
    methodKind: "bidi_streaming";
    input: typeof ScoreIntervalRequestSchema;
    output: typeof ScoreIntervalResponseSchema;
  },
  /**
   * Score a variant for a genomic interval.
   *
   * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.ScoreVariant
   */
  scoreVariant: {
    methodKind: "bidi_streaming";
    input: typeof ScoreVariantRequestSchema;
    output: typeof ScoreVariantResponseSchema;
  },
  /**
   * Score ISM variant effect predictions for a genomic interval.
   *
   * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.ScoreIsmVariant
   */
  scoreIsmVariant: {
    methodKind: "bidi_streaming";
    input: typeof ScoreIsmVariantRequestSchema;
    output: typeof ScoreIsmVariantResponseSchema;
  },
  /**
   * Get metadata for the model.
   *
   * @generated from rpc google.gdm.gdmscience.alphagenome.v1main.DnaModelService.GetMetadata
   */
  getMetadata: {
    methodKind: "server_streaming";
    input: typeof MetadataRequestSchema;
    output: typeof MetadataResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_alphagenome_protos_dna_model_service, 0);

