// Copyright 2024 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file alphagenome/protos/tensor.proto (package google.gdm.gdmscience.alphagenome.v1main, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file alphagenome/protos/tensor.proto.
 */
export const file_alphagenome_protos_tensor: GenFile = /*@__PURE__*/
  fileDesc("Ch9hbHBoYWdlbm9tZS9wcm90b3MvdGVuc29yLnByb3RvEihnb29nbGUuZ2RtLmdkbXNjaWVuY2UuYWxwaGFnZW5vbWUudjFtYWluIsgBCgZUZW5zb3ISDQoFc2hhcGUYASADKAUSRQoJZGF0YV90eXBlGAIgASgOMjIuZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5EYXRhVHlwZRJGCgVhcnJheRgDIAEoCzI1Lmdvb2dsZS5nZG0uZ2Rtc2NpZW5jZS5hbHBoYWdlbm9tZS52MW1haW4uVGVuc29yQ2h1bmtIABIVCgtjaHVua19jb3VudBgEIAEoA0gAQgkKB3BheWxvYWQicAoLVGVuc29yQ2h1bmsSDAoEZGF0YRgBIAEoDBJTChBjb21wcmVzc2lvbl90eXBlGAIgASgOMjkuZ29vZ2xlLmdkbS5nZG1zY2llbmNlLmFscGhhZ2Vub21lLnYxbWFpbi5Db21wcmVzc2lvblR5cGUqlQIKCERhdGFUeXBlEhkKFURBVEFfVFlQRV9VTlNQRUNJRklFRBAAEhYKEkRBVEFfVFlQRV9CRkxPQVQxNhABEhUKEURBVEFfVFlQRV9GTE9BVDE2EAsSFQoRREFUQV9UWVBFX0ZMT0FUMzIQAhIVChFEQVRBX1RZUEVfRkxPQVQ2NBADEhIKDkRBVEFfVFlQRV9JTlQ4EAQSEwoPREFUQV9UWVBFX0lOVDMyEAUSEwoPREFUQV9UWVBFX0lOVDY0EAYSEwoPREFUQV9UWVBFX1VJTlQ4EAcSFAoQREFUQV9UWVBFX1VJTlQzMhAIEhQKEERBVEFfVFlQRV9VSU5UNjQQCRISCg5EQVRBX1RZUEVfQk9PTBAKKkcKD0NvbXByZXNzaW9uVHlwZRIZChVDT01QUkVTU0lPTl9UWVBFX05PTkUQABIZChVDT01QUkVTU0lPTl9UWVBFX1pTVEQQAUKSAQosY29tLmdvb2dsZS5nZG0uZ2Rtc2NpZW5jZS5hbHBoYWdlbm9tZS52MW1haW5CC1RlbnNvclByb3RvUAFaU2dvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvZ2RtL2dkbXNjaWVuY2UvYWxwaGFnZW5vbWUvdjFtYWluO2FscGhhZ2Vub21lYgZwcm90bzM");

/**
 * Protocol buffer representing an arbitrarily large multi-dimensional array of
 * data, laid out in row-major format. To support tensors larger than the
 * maximum protocol buffer message size, the tensor payload may be split into
 * multiple chunks.
 *
 * @generated from message google.gdm.gdmscience.alphagenome.v1main.Tensor
 */
export type Tensor = Message<"google.gdm.gdmscience.alphagenome.v1main.Tensor"> & {
  /**
   * The shape of the tensor. If empty, the data will be treated as a scalar.
   *
   * @generated from field: repeated int32 shape = 1;
   */
  shape: number[];

  /**
   * Data type for the elements in this tensor.
   *
   * @generated from field: google.gdm.gdmscience.alphagenome.v1main.DataType data_type = 2;
   */
  dataType: DataType;

  /**
   * The payload for the tensor.
   *
   * @generated from oneof google.gdm.gdmscience.alphagenome.v1main.Tensor.payload
   */
  payload: {
    /**
     * The raw data for the tensor. If present, the tensor is not split into
     * chunks.
     *
     * @generated from field: google.gdm.gdmscience.alphagenome.v1main.TensorChunk array = 3;
     */
    value: TensorChunk;
    case: "array";
  } | {
    /**
     * The number of chunks the tensor is split into.
     *
     * @generated from field: int64 chunk_count = 4;
     */
    value: bigint;
    case: "chunkCount";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message google.gdm.gdmscience.alphagenome.v1main.Tensor.
 * Use `create(TensorSchema)` to create a new message.
 */
export const TensorSchema: GenMessage<Tensor> = /*@__PURE__*/
  messageDesc(file_alphagenome_protos_tensor, 0);

/**
 * A single chunk of a tensor.
 *
 * @generated from message google.gdm.gdmscience.alphagenome.v1main.TensorChunk
 */
export type TensorChunk = Message<"google.gdm.gdmscience.alphagenome.v1main.TensorChunk"> & {
  /**
   * Flattened tensor data. Data is laid out in row-major order.
   *
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;

  /**
   * How the data is compressed. Compression is applied to each chunk
   * independently.
   *
   * @generated from field: google.gdm.gdmscience.alphagenome.v1main.CompressionType compression_type = 2;
   */
  compressionType: CompressionType;
};

/**
 * Describes the message google.gdm.gdmscience.alphagenome.v1main.TensorChunk.
 * Use `create(TensorChunkSchema)` to create a new message.
 */
export const TensorChunkSchema: GenMessage<TensorChunk> = /*@__PURE__*/
  messageDesc(file_alphagenome_protos_tensor, 1);

/**
 * The data type of the tensor.
 *
 * @generated from enum google.gdm.gdmscience.alphagenome.v1main.DataType
 */
export enum DataType {
  /**
   * Unspecified data type.
   *
   * @generated from enum value: DATA_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 16-bit "Brain Floating Point". See
   * https://en.wikipedia.org/wiki/Bfloat16_floating-point_format for more
   * details.
   *
   * @generated from enum value: DATA_TYPE_BFLOAT16 = 1;
   */
  BFLOAT16 = 1,

  /**
   * 16-bit floating point.
   *
   * @generated from enum value: DATA_TYPE_FLOAT16 = 11;
   */
  FLOAT16 = 11,

  /**
   * 32-bit floating point.
   *
   * @generated from enum value: DATA_TYPE_FLOAT32 = 2;
   */
  FLOAT32 = 2,

  /**
   * 64-bit floating point.
   *
   * @generated from enum value: DATA_TYPE_FLOAT64 = 3;
   */
  FLOAT64 = 3,

  /**
   * 8-bit signed integer.
   *
   * @generated from enum value: DATA_TYPE_INT8 = 4;
   */
  INT8 = 4,

  /**
   * 32-bit signed integer.
   *
   * @generated from enum value: DATA_TYPE_INT32 = 5;
   */
  INT32 = 5,

  /**
   * 64-bit signed integer.
   *
   * @generated from enum value: DATA_TYPE_INT64 = 6;
   */
  INT64 = 6,

  /**
   * 8-bit unsigned integer.
   *
   * @generated from enum value: DATA_TYPE_UINT8 = 7;
   */
  UINT8 = 7,

  /**
   * 32-bit unsigned integer.
   *
   * @generated from enum value: DATA_TYPE_UINT32 = 8;
   */
  UINT32 = 8,

  /**
   * 64-bit unsigned integer.
   *
   * @generated from enum value: DATA_TYPE_UINT64 = 9;
   */
  UINT64 = 9,

  /**
   * 8-bit boolean.
   *
   * @generated from enum value: DATA_TYPE_BOOL = 10;
   */
  BOOL = 10,
}

/**
 * Describes the enum google.gdm.gdmscience.alphagenome.v1main.DataType.
 */
export const DataTypeSchema: GenEnum<DataType> = /*@__PURE__*/
  enumDesc(file_alphagenome_protos_tensor, 0);

/**
 * Compression type for the tensor data.
 *
 * @generated from enum google.gdm.gdmscience.alphagenome.v1main.CompressionType
 */
export enum CompressionType {
  /**
   * No compression.
   *
   * @generated from enum value: COMPRESSION_TYPE_NONE = 0;
   */
  NONE = 0,

  /**
   * ZSTD compression.
   *
   * @generated from enum value: COMPRESSION_TYPE_ZSTD = 1;
   */
  ZSTD = 1,
}

/**
 * Describes the enum google.gdm.gdmscience.alphagenome.v1main.CompressionType.
 */
export const CompressionTypeSchema: GenEnum<CompressionType> = /*@__PURE__*/
  enumDesc(file_alphagenome_protos_tensor, 1);

